### PR TITLE
Add SonarQube config to README

### PR DESCRIPTION
**Pull request by alexashley**

### CODE REVIEW

**Comment by mrparkers** [comment]
Thanks for this.  Could you also update the local Terragrunt config that would reference `sonar.localhost` while you're here?  https://github.com/rode/demo/blob/main/tf/local/terragrunt.hcl

**Comment by alexashley** [comment]
@mrparkers I set those flags in `tf/local`, although I've just been applying `tf/environments/local`, where it was [already configured](https://github.com/rode/demo/blob/534a0f96fe98846d8e8ad9e7a69162e735532dd6/tf/environments/local/terragrunt.hcl#L28-L29) for `sonarqube.localhost`.

**Comment by mrparkers** [comment]
Haha, you can tell that I use the local environment quite a bit 😄  my bad, maybe we should remove the duplicate file so it isn't confusing in the future.  I'll approve with or without that change though.

**Review by mrparkers — APPROVED** [review]

**Comment by alexashley** [comment]
@mrparkers I ended up removing `tf/local`

**Pull request merged**
